(function(){
var h=function(a,c,b){b=Math.min(Math.max(b,0),1);return[Math.round(b*a[0]+(1-b)*c[0]),Math.round(b*a[1]+(1-b)*c[1]),Math.round(b*a[2]+(1-b)*c[2])]},s=function(a,c){var b=[0,0,0];return h(b,a,c)};var u=function(a){var c=parseInt(a.substr(1,2),16),b=parseInt(a.substr(3,2),16),d=parseInt(a.substr(5,2),16);return[c,b,d]},v=function(a,c){var b,d;if(a[2]<=0.5)b=a[1]*a[2];else b=a[1]*(1-a[2]);if(c[2]<=0.5)d=c[1]*c[2];else d=c[1]*(1-c[2]);var e=a[0]/360,f=c[0]/360,g=(e-f)*2*Math.PI;return(a[2]-c[2])*(a[2]-
c[2])+b*b+d*d-2*b*d*Math.cos(g)},w=function(a,c){var b=[255,255,255];return h(b,a,c)},y=function(a,c,b){a=Number(a);c=Number(c);b=Number(b);if(isNaN(a)||a<0||a>255||isNaN(c)||c<0||c>255||isNaN(b)||b<0||b>255)throw Error("'("+a+","+c+","+b+"') is not a valid RGB color");var d=x(a.toString(16)),e=x(c.toString(16)),f=x(b.toString(16));return"#"+d+e+f},B=function(a,c,b){var d=a/255,e=c/255,f=b/255,g=Math.max(d,e,f),j=Math.min(d,e,f),i=0,l=0,k=0.5*(g+j);if(g!=j){if(g==d)i=60*(e-f)/(g-j);else if(g==e)i=
60*(f-d)/(g-j)+120;else if(g==f)i=60*(d-e)/(g-j)+240;if(0<k&&k<=0.5)l=(g-j)/(2*k);else l=(g-j)/(2-2*k)}return[Math.round(i+360)%360,l,k]},x=function(a){return a.length==1?"0"+a:a};function C(a,c,b,d,e,f,g,j,i,l,k,m,n,o,p,q,r,t,z,A,E,F){this.c=a;this.U=c;this.b=b;this.a=d;this.v=e;this.u=f;this.T=g;this.F=l;this.m=k;this.R=m;this.K=j;this.L=i;this.W=n;this.V=o;this.M=p;this.S=q;this.k=r;this.Q=t;this.P=z;this.O=A;this.Y=E||z;this.X=F||A;this.e=[];this.d=0;this.j=false;this.Z=this.c.offsetHeight}C.prototype.init=function(){var a=[],c=0;for(var b=this.c.firstChild;b;b=b.nextSibling)if(b.nodeType==1&&b.tagName=="LI"){var d=document.getElementById("taw"+c),e=this.i("a","adt",d)[0],
f=this.i("span",null,d)[0],g=this.i("div","adb",d)[0],j=this.i("span","adus",d)[0],i=this.z(c++,e.href,f.innerHTML,g.innerHTML,j.innerHTML);a.push(i)}this.e.push(a);this.J();this.I();this.U.style.display="block"};C.prototype.g="";C.prototype.h="";C.prototype.l="";var D=13;C.prototype.D=function(a){var c=0;for(var b=0;b<this.e.length;b++)c+=this.e[b].length;this.k=a.token&&a.token.length>0?a.token:null;var d=[];for(var b=0;b<a.ads.length;b++){var e=a.ads[b];e.id=c+b;d[b]=e}this.e.push(d);this.d++;
this.n(d);this.p();this.j=false};C.prototype.w=function(a,c,b,d){var e=document.createElement("li"),f="ss('','aw"+a.id+"')";e.id="taw"+a.id;e.setAttribute("onfocus",f);e.setAttribute("onmouseover",f);e.style.height=c?c+"px":"";e.style.width=b?b+"px":"";var g=document.createElement("div");g.className="ad";e.appendChild(g);var j;if(this.m==1){var i,l,k,m;i=document.createElement("table");i.setAttribute("cellpadding",0);i.setAttribute("cellspacing",0);i.setAttribute("border",0);i.className="adc";i.style.height=
c?c+"px":"";i.style.width=b?b+"px":"";g.appendChild(i);l=document.createElement("tbody");k=document.createElement("tr");m=document.createElement("td");m.setAttribute("valign","middle");k.appendChild(m);l.appendChild(k);i.appendChild(l);j=m}else j=g;var n=d?this.Y:this.P,o=d?this.X:this.O,p="font-size: "+n+"px",q="font-size: "+o+"px",r="<a class=adt href="+a.url+" id=aw"+a.id+" onclick=\"ha('aw"+a.id+'\')" onfocus="'+f+'" onmousedown="st(\'aw'+a.id+'\')" onmouseover="return '+f+'" target=_top><span style="'+
p+'">'+a.title+'</span></a><div class=adb style="'+q+'">'+a.text+"</div><div class=adu><span class=adus id=uaw"+a.id+" onclick=ga(this,event) onmousedown=st(this.id.substr(1))>"+a.visibleUrl+"</span></div>";j.innerHTML=r;return e};C.prototype.z=function(a,c,b,d,e){var f={};f.id=a;f.url=c;f.title=b;f.text=d;f.visibleUrl=e;return f};C.prototype.A=function(){this.c.innerHTML='<li style="width:100%" id='+this.V+"><table><tbody><tr><td>"+this.W+"</td></tr></tbody></table>"};C.prototype.i=function(a,c,
b){var d=b.getElementsByTagName(a),e=[];for(var f=0,g;g=d[f];f++){var j=g.className;if(j.split(" ").indexOf(c)>=0)e.push(g)}return e.length?e:d};C.prototype.q=function(a){if(a==0&&this.d>0)this.t(this.C);else if(a==1&&(this.k||this.d<this.e.length-1))this.t(this.B)};C.prototype.r=function(a){this.o(a)};C.prototype.s=function(a){if(a==0&&this.d>0||a==1&&(this.k||this.d<this.e.length-1))this.H(a)};C.prototype.n=function(a){var c=0;for(var b=0;b<this.d;b++)c+=this.e[b].length;var d,e;if(this.m==0)e=
Math.floor(this.c.offsetWidth/a.length);else if(this.m==1&&this.Q)d=Math.round(this.N/a.length);while(this.c.firstChild)this.c.removeChild(this.c.firstChild);for(var b=0;b<a.length;b++){var f=this.w(a[b],d,e,this.F==a.length);this.c.appendChild(f)}};C.prototype.B=function(){if(this.d==this.e.length-1){this.A();this.G(window.location.search)}else{var a=this.e[++this.d];this.n(a);this.p();this.j=false}};C.prototype.C=function(){var a=this.e[--this.d];this.n(a);this.p();this.j=false};C.prototype.t=function(a){if(!this.j){this.j=
true;this.N=this.c.parentNode.offsetHeight;while(this.c.firstChild)this.c.removeChild(this.c.firstChild)}a.call(this)};C.prototype.G=function(a){if(this.g==""||this.h==""||this.l==""){if(a.charAt(0)=="?")a=a.substring(1);var c=a.split("&");for(var b=0;b<c.length;b++){var d=c[b].split("=");if(d.length==2)switch(d[0]){case "client":this.g=d[1];break;case "format":this.h=d[1];break;case "url":this.l=d[1];break}}}var e="/pagead/ads?output=smajs&targeting=content&ad_type=text&num_ads="+this.F+"&tok="+
this.k;if(this.g)e+="&client="+this.g;if(this.h)e+="&format=sma-"+this.h;if(this.l)e+="&url="+this.l;var f=document.createElement("script");f.setAttribute("type","text/javascript");f.setAttribute("src",e);var g=document.getElementsByTagName("head")[0];g.appendChild(f)};C.prototype.H=function(a){var c=a==0?this.b:this.a;c.style.backgroundColor=c.activeBgColor;c.style.cursor=c.activeCursor};C.prototype.o=function(a){var c=a==0?this.b:this.a;c.style.backgroundColor=c.inactiveBgColor;c.style.cursor=c.inactiveCursor};
C.prototype.p=function(){if(this.d>0)this.b.onmouseover=this.b.activeMouseOver;else{this.b.onmouseover=null;this.o(0)}if(this.k||this.d<this.e.length-1)this.a.onmouseover=this.a.activeMouseOver;else{this.a.onmouseover=null;this.o(1)}};C.prototype.I=function(){this.b.f=this;this.b.activeCursor=this.K;this.b.inactiveCursor=this.L;this.b.onmousedown=function(){this.f.q(0)};this.b.activeMouseOver=function(){this.f.s(0)};this.b.onmouseout=function(){this.f.r(0)};this.b.onmouseover=this.b.activeMouseOver;
this.b.onmouseout();this.a.f=this;this.a.activeCursor=this.K;this.a.inactiveCursor=this.L;this.a.onmousedown=function(){this.f.q(1)};this.a.activeMouseOver=function(){this.f.s(1)};this.a.onmouseout=function(){this.f.r(1)};this.a.onmouseover=this.a.activeMouseOver;this.a.onmouseout()};C.prototype.J=function(){var a,c,b=u(this.u);if(this.v==this.u){a=u(this.T);c=B(a[0],a[1],a[2])[2]}else{var d=B(b[0],b[1],b[2]),e=u(this.v),f=B(e[0],e[1],e[2]),g=v(d,f);if(g<=0.02){a=f[2]<=d[2]?s(e,0.35):w(e,0.35);var j=
B(a[0],a[1],a[2]);c=j[2]}else{a=e;c=f[2]}}var i=y(a[0],a[1],a[2]),l=h(a,b,this.R),k=y(l[0],l[1],l[2]),m=c>0.5?0:1,n,o;if(this.m==0)if(this.S){n=3;o=2}else{n=2;o=3}else{n=1;o=0}var p=[],q=[];p[0]=n*D;p[1]=m*D;q[0]=o*D;q[1]=m*D;var r=document.createElement("img");r.src=this.M;var t=i+" url("+this.M+") no-repeat ";this.b.style.background=t+"-"+p[0]+"px -"+p[1]+"px";this.a.style.background=t+"-"+q[0]+"px -"+q[1]+"px";this.b.activeBgColor=i;this.b.inactiveBgColor=k;this.a.activeBgColor=i;this.a.inactiveBgColor=
k};if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a){for(var c=0;c<this.length;c++)if(this[c]==a)return c;return-1};if(window.sma){window.smaSlotManager=new C(document.getElementById(sma[0]),document.getElementById(sma[1]),document.getElementById(sma[2]),document.getElementById(sma[3]),sma[4],sma[5],sma[6],sma[7],sma[8],sma[9],sma[10],sma[11],sma[12],sma[13],sma[14],sma[15],sma[16],sma[17],sma[18],sma[19],sma[20],sma[21]);window.smaSlotManager.init();window.handleAdsRequestDone=function(a){window.smaSlotManager.D(a)}};
})()
