#!/bin/bash

change_path()
{	
    ext=pstex
    file=$1.${ext}_t
    if [ -f $file ]; then
	filePath=fig/$1.${ext}
	filePath2=$( echo ${filePath} | sed -e 's/\//\\\//g' )
	echo "s/includegraphics{.*}/includegraphics{${filePath2}}/" > cmd
	sed -f cmd $file > trans
	rm cmd
	mv trans $file
    else
	echo error;
    fi
}

WORK_DIR=`pwd`
echo WORK_DIR: $WORK_DIR
BASE_DIR=`dirname $WORK_DIR$` 
echo BASE_DIR: $BASE_DIR
CHAP_DIR=`basename $BASE_DIR`
echo CHAP_DIR: $CHAP_DIR
LN_DIR=${WORK_DIR}/../../../fig
echo LN_DIR:   $LN_DIR

rm -f fig/*
for chap in 0-begin 1-intro 2-motiv 3-proto 4-rtos 5-imp; do
    path="chapter/${chap}/fig"
    for ext in eps tex pstex pstex_t ;do
	for path_file in `ls ${path}/*.${ext}` ; do
	    echo $path_file 
	    file=`basename $path_file`
	    ln -sfv ../$path_file fig/$file
	done
    done
done

exit 0
      ln -sfv ../chapter/$CHAP_DIR/fig/${base}.pstex ${base}.pstex
      cd ${WORK_DIR}

