#!/bin/bash
cd /Users/paul/Documents/Pesquisa/Master/dissert
arq="main"
rm *.dvi *.ps *.log *.ps *.pdf
file=$arq.tex
if [ -f $file ]; then
  echo  $file
  latex $file
  dvips -o $arq.ps $arq.dvi
  epstopdf $arq.ps
#  open $1.pdf
else
  echo $file "n'existe pas"
fi
