#!/bin/bash
rm *.dvi *.ps *.log *.ps *.pdf
file=$1.tex
if [ -f $file ]; then
  echo  $file
  latex $file
  dvips -o $1.eps $1.dvi
  epstopdf $1.eps
#  evince $1.pdf
else
  echo $file "n'existe pas"
fi
