#!/bin/bash
ext=tex

change_path()
{
    fig=$1
    fig_base=`basename $fig .tex`
    echo $fig_base $fig

    if [ -f $fig ] && ! grep "fig/$fig_base" $fig > /dev/null ; then
	echo Updating fig path
	fig_path=fig/$fig_base
	fig_path2=$( echo ${fig_path} | sed -e 's/\//\\\//g' )
	echo $fig_path
	echo $fig_path2
	echo "s/includegraphics{$fig_base}/includegraphics{$fig_path2}/" > cmd
	sed -f cmd $fig > trans
	rm cmd
	mv trans $fig
    else
	echo No fig file to update;
    fi
}

for i in $(find `pwd` -name '*.eps'); do
    echo `dirname $i`
    cd  `dirname $i`
    ls *.eps
#    gnuplot `basename $i`
#   echo `basename $i .gp`.tex
#   change_path `basename $i .gp`.tex
#   cp *.tex *.eps ~/Master/gnuplot/ppnet/synt/fig
#   cp *.tex *.eps ~/master/chapter/5-rtos/fig
done
