#!/bin/bash
rm *.dvi *.ps *.log *.ps *.pdf
file=$1.tex
if [ -f $file ]; then
  echo  $file
  latex $file
  dvips -t a4 -o $1.ps $1.dvi
  ps2pdf $1.ps
  evince $1.pdf
else
  echo $file "n'existe pas"
fi
