#!/bin/bash
ext=tex

change_path()
{
    fig=$1
    fig_base=`basename $fig .tex`
    echo $fig_base

    if [ -f $fig ] && ! grep "fig/$fig_base" $fig > /dev/null ; then
	echo Updating fig path
	fig_path=fig/$fig_base
	fig_path2=$( echo ${fig_path} | sed -e 's/\//\\\//g' )
	echo $fig_path
	echo $fig_path2
	echo "s/includegraphics{$fig_base}/includegraphics{$fig_path2}/" > cmd
	sed -f cmd $fig > trans
	rm cmd
	mv trans $fig
    else
	echo No fig file to update;
    fi
}

rm *.dvi *.ps *.log *.ps *.pdf

cd fig
for i in `ls *.gp`; do
    echo $i
    gnuplot $i
done

for i in `ls *.$ext`; do
    echo $i
    change_path $i
done
cd ..

file=$1.tex
if [ -f $file ]; then
  echo  $file
  latex $file
  dvips -o $1.ps $1.dvi
  ps2pdf $1.ps
  evince $1.pdf
else
  echo $file "n'existe pas"
fi
