#!/bin/bash
ext=tex

change_path()
{
    fig=$1
    fig_base=`basename $fig .tex`
    echo $fig_base $fig

    if [ -f $fig ] && ! grep "fig/${fig_base}.pdf" $fig > /dev/null ; then
	echo Updating fig name
	fig_name=${fig_base}.pdf
	echo $fig_name
	echo "s/$fig_base}/$fig_name}/" > cmd
	sed -f cmd $fig > trans
	rm cmd
	mv trans $fig
    else
	echo No fig file to update;
    fi
}

for i in $(find `pwd` -name '*.tex'); do
#    echo $i
    echo `dirname $i`
    cd  `dirname $i`
    echo  `basename $i`
#   echo `basename $i .gp`.tex
   change_path `basename $i`
#   cp *.tex *.eps ~/Master/gnuplot/ppnet/synt/fig
#   cp *.tex *.eps ~/master/chapter/5-rtos/fig
done
