#!/bin/bash

change_path()
{	
    ext=pstex
    file=$1.${ext}_t
    if [ -f $file ]; then
	filePath=fig/$1.${ext}
	filePath2=$( echo ${filePath} | sed -e 's/\//\\\//g' )
	echo "s/includegraphics{.*}/includegraphics{${filePath2}}/" > cmd
	sed -f cmd $file > trans
	rm cmd
	mv trans $file
    else
	echo error;
    fi
}

WORK_DIR=`pwd`
echo WORK_DIR: $WORK_DIR
BASE_DIR=`dirname $WORK_DIR$` 
echo BASE_DIR: $BASE_DIR
CHAP_DIR=`basename $BASE_DIR`
echo CHAP_DIR: $CHAP_DIR
LN_DIR=${WORK_DIR}/../../../fig
echo LN_DIR:   $LN_DIR

for i in `ls *.tex`; do
      base=`basename "$i" '.tex'`
      echo $base
#     change_path $base
      cd ${LN_DIR}
      ln -sfv ../chapter/$CHAP_DIR/fig/${base}.tex ${base}.tex
      ln -sfv ../chapter/$CHAP_DIR/fig/${base}.eps ${base}.eps
      cd ${WORK_DIR}
done
